"""create initial tables

Revision ID: 67411b5e3ad9
Revises: 
Create Date: 2026-09-24 03:38:51.217825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67411b5e3ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate <= 1', name=op.f('ck_merchants_commission_rate_range')),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchants'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('num_installments', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('num_installments > 0', name=op.f('ck_orders_num_installments_positive')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_orders_total_amount_positive')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], name=op.f('fk_orders_merchant_id_merchants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('installments',
    sa.Column('installment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'overdue', 'cancelled')", name=op.f('ck_installments_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_installments_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_installments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installment_id', name=op.f('pk_installments'))
    )
    op.create_index(op.f('ix_installments_due_date'), 'installments', ['due_date'], unique=False)
    op.create_index(op.f('ix_installments_order_id'), 'installments', ['order_id'], unique=False)
    op.create_index(op.f('ix_installments_status'), 'installments', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('installment_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.installment_id'], name=op.f('fk_payments_installment_id_installments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_installment_id'), 'payments', ['installment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_installment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_installments_status'), table_name='installments')
    op.drop_index(op.f('ix_installments_order_id'), table_name='installments')
    op.drop_index(op.f('ix_installments_due_date'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('merchants')
    # ### end Alembic commands ###
